export const Pages=[
    {
        time:15000,
        data:{
            type:"div",
            classes:["welcome-page-container"],
            content:[
                {
                    type:"div",
                    classes:["welcome-page-text","welcome-page-animation"],
                    text:"Welcome to ",
                    content:[
                        {
                            type:"span",
                            text:"Pradeep's Page"
                        }
                    ]
                },
            ]
        }
    },
    {
        time:24000,
        data:{
            type:"div",
            classes:["page-container"],
            content:[
                {
                    type:"div",
                    classes:["section-1"]
                },
                {
                    type:"div",
                    classes:["section-2"]
                },
                {
                    type:"div",
                    classes:["content-container"],
                    content:[
                        {
                            type:"div",
                            classes:["content-title"],
                            text:"My Family",
                            cssText:"grid-area:1/9/3/11;"
                        },
                        {
                            type:"img",
                            classes:["children","image-clip","animate-BW"],
                            attr:{src:"images/children_BW.png"},
                            cssText:"grid-column-start:3;grid-row-start:4;--d:2s"
                        },
                        {
                            type:"img",
                            classes:["children","image-clip","animate-col"],
                            attr:{src:"images/children.png"},
                            cssText:"grid-column-start:3;grid-row-start:4;--d:2s"
                        },
                        {
                            type:"img",
                            classes:["uncle","image-clip","animate-BW"],
                            attr:{src:"images/uncle_BW.png"},
                            cssText:"grid-column-start:16;grid-row-start:6;--d:4s"
                        },
                        {
                            type:"img",
                            classes:["uncle","image-clip","animate-col"],
                            attr:{src:"images/uncle.png"},
                            cssText:"grid-column-start:16;grid-row-start:6;--d:4s"
                        },
                        {
                            type:"img",
                            classes:["family","image-clip","animate-BW"],
                            attr:{src:"images/family_BW.png"},
                            cssText:"grid-column-start:10;grid-row-start:8;--d:6s"
                        },
                        {
                            type:"img",
                            classes:["family","image-clip","animate-col"],
                            attr:{src:"images/family.png"},
                            cssText:"grid-column-start:10;grid-row-start:8;--d:6s"
                        }
                    ]
                }
            ]
        }
    },
    {
        time:12500,
        data:{
            type:"div",
            classes:["page-container"],
            content:[
                {
                    type:"div",
                    classes:["section-10"]
                },
                {
                    type:"div",
                    classes:["section-11"]
                },
                {
                    type:"div",
                    classes:["content-container"],
                    content:[
                        {
                            type:"div",
                            classes:["content-title"],
                            text:"Technology",
                            cssText:"grid-area:1/10/3/12;"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/html.png"},
                            cssText:"grid-column-start:7;grid-row-start:4;--d:3s"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/css.png"},
                            cssText:"grid-column-start:9;grid-row-start:4;--d:3.2s"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/js.png"},
                            cssText:"grid-column-start:11;grid-row-start:4;--d:3.4s"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/php.png"},
                            cssText:"grid-column-start:13;grid-row-start:4;--d:3.6s"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/java.png"},
                            cssText:"grid-column-start:7;grid-row-start:8;--d:3.4s"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/Android.png"},
                            cssText:"grid-column-start:9;grid-row-start:8;--d:3.6s"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/csharp.png"},
                            cssText:"grid-column-start:11;grid-row-start:8;--d:3.8s"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/maui.png"},
                            cssText:"grid-column-start:13;grid-row-start:8;--d:4s"
                        },                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/python.png"},
                            cssText:"grid-column-start:7;grid-row-start:12;--d:3.8s"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/Ruby.png"},
                            cssText:"grid-column-start:9;grid-row-start:12;--d:4s"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/linux.png"},
                            cssText:"grid-column-start:11;grid-row-start:12;--d:4.2s"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/sql.png"},
                            cssText:"grid-column-start:13;grid-row-start:12;--d:4.4s"
                        },                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/node.png"},
                            cssText:"grid-column-start:7;grid-row-start:16;--d:4.2s"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/react.png"},
                            cssText:"grid-column-start:9;grid-row-start:16;--d:4.4s"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/mongodb.png"},
                            cssText:"grid-column-start:11;grid-row-start:16;--d:4.6s"
                        },
                        {
                            type:"img",
                            classes:["tech","image-clip","animate-tech"],
                            attr:{src:"images/expressserver.png"},
                            cssText:"grid-column-start:13;grid-row-start:16;--d:4.8s"
                        }
                    ]
                }
            ]
        }
    },
    {
        time:20000,
        data:{
            type:"div",
            classes:["page-container"],
            content:[
                {
                    type:"div",
                    classes:["section-3"]
                },
                {
                    type:"div",
                    classes:["section-4"]
                },
                {
                    type:"div",
                    classes:["content-container"],
                    content:[
                        {
                            type:"div",
                            classes:["content-title"],
                            text:"Food",
                            cssText:"grid-area:1/9/1/10;"
                        },
                        {
                            type:"img",
                            classes:["food","image-clip","animate-BW"],
                            attr:{src:"images/aloogobi_BW.png"},
                            cssText:"grid-column-start:3;grid-row-start:4;--d:2s"
                        },
                        {
                            type:"img",
                            classes:["food","image-clip","animate-col"],
                            attr:{src:"images/aloogobi.png"},
                            cssText:"grid-column-start:3;grid-row-start:4;--d:2s"
                        },
                        {
                            type:"img",
                            classes:["food","image-clip","animate-BW"],
                            attr:{src:"images/chickencurry_BW.png"},
                            cssText:"grid-column-start:13;grid-row-start:7;--d:4s"
                        },
                        {
                            type:"img",
                            classes:["food","image-clip","animate-col"],
                            attr:{src:"images/chickencurry.png"},
                            cssText:"grid-column-start:13;grid-row-start:7;--d:4s"
                        }
                        ,
                        {
                            type:"img",
                            classes:["food","image-clip","animate-BW"],
                            attr:{src:"images/fishandchips_BW.png"},
                            cssText:"grid-column-start:5;grid-row-start:12;--d:6s"
                        },
                        {
                            type:"img",
                            classes:["food","image-clip","animate-col"],
                            attr:{src:"images/fishandchips.png"},
                            cssText:"grid-column-start:5;grid-row-start:12;--d:6s"
                        }
                    ]
                }
            ]
        }
    },
    {
        time:20000,
        data:{
                type:"div",
                classes:["page-container"],
                content:[
                {
                    type:"div",
                    classes:["section-5"]
                },
                {
                    type:"div",
                    classes:["section-6"]
                },
                {
                    type:"div",
                    classes:["content-container"],
                    content:[
                        {
                            type:"div",
                            classes:["content-title"],
                            text:"Heroes",
                            cssText:"grid-area:1/9/1/11;"
                        },
                        {
                            type:"img",
                            classes:["hero","image-clip","animate-BW"],
                            attr:{src:"images/spock_BW.png"},
                            cssText:"grid-column-start:4;grid-row-start:4;--d:2s"
                        },
                        {
                            type:"img",
                            classes:["hero","image-clip","animate-col"],
                            attr:{src:"images/spock.png"},
                            cssText:"grid-column-start:4;grid-row-start:4;--d:2s"

                        },
                        {
                            type:"img",
                            classes:["uncle","image-clip","animate-BW"],
                            attr:{src:"images/johnconstantine_BW.png"},
                            cssText:"grid-column-start:15;grid-row-start:6;--d:4s"

                        },
                        {
                            type:"img",
                            classes:["uncle","image-clip","animate-col"],
                            attr:{src:"images/johnconstantine.png"},
                            cssText:"grid-column-start:15;grid-row-start:6;--d:4s"
                        },
                        {
                            type:"img",
                            classes:["hero","image-clip","animate-BW"],
                            attr:{src:"images/jonnybarnes_BW.png"},
                            cssText:"grid-column-start:8;grid-row-start:12;--d:6s"
                        },
                        {
                            type:"img",
                            classes:["hero","image-clip","animate-col"],
                            attr:{src:"images/jonnybarnes.png"},
                            cssText:"grid-column-start:8;grid-row-start:12;--d:6s"
                        }
                    ]
                }
            ]
        }
    },
    {
        time:10000,
        data:{
            type:"div",
            classes:["welcome-page-container"],
            content:[
                {
                    type:"div",
                    classes:["welcome-page-text","exit-page-animation"],
                    text:"Thanks for watching",
                },
            ]
        }
    }
];